In [6]:
import numpy as np
import scipy

In [68]:
input = """19, 13, 30 @ -2,  1, -2
18, 19, 22 @ -1, -1, -2
20, 25, 34 @ -2, -2, -4
12, 31, 28 @ -1, -2, -1
20, 19, 15 @  1, -5, -3"""

test_area = np.array([[7, 27], [7, 27]])

In [140]:
input = """364193859817003, 337161998875178, 148850519939119 @ 85, 85, 473
222402516161891, 289638719990878, 261939904566871 @ 123, -40, 25
219626703416113, 76777384100180, 165418060594769 @ 115, 317, 193
334014037912851, 277570220219582, 209375720159907 @ -121, -80, 116
287190980765131, 255535497710972, 312523085347417 @ 109, 124, -140
234886861358651, 242049831142762, 284674462721087 @ 30, -13, 12
318123114620241, 57779289415022, 104021426110157 @ 38, 649, 396
414924365272846, 347098380764754, 274815913131088 @ -212, -85, -76
178659733911043, 235997257427522, 329124085782047 @ 44, -46, -19
305237792764107, 250686948592234, 309852066718257 @ -19, 35, -64
273597981930275, 440308709640186, 469786981522303 @ 32, -307, -343
408324200512731, 406186314332306, 243659676144735 @ -57, -434, -335
353587787512041, 133063636294234, 291877578038455 @ -102, 267, -37
381538409034485, 424997194110414, 537617243846654 @ -121, -313, -786
306523697831995, 294246226942834, 164419077114479 @ -5, -30, 207
324536437745401, 191030021321036, 336769950084347 @ -57, 137, -109
414437864157483, 335608119431914, 356138167714543 @ -219, -138, -100
194637239433443, 276858325517959, 350377510800947 @ 69, -70, -69
286311519528811, 153419693551982, 223625295132227 @ -83, 36, 100
238624464051303, 239071356097028, 325758797908716 @ 65, 25, -70
333534654425921, 345127785099412, 256812393234547 @ 147, -19, -77
296498032678335, 239750443615962, 287084234612903 @ -16, 39, -15
287544310033611, 106465086128987, 318441225133128 @ -67, 124, -16
405972576883723, 437422586014750, 366352157899221 @ -179, -379, -418
396340222055150, 215672150064519, 210066160671444 @ -178, 146, 118
281922711821881, 127132890108528, 352372300786783 @ -92, 38, -25
327578075797476, 334421013119088, 284492625744456 @ 8, -75, -70
302145622305035, 215191881172538, 349853222296631 @ -51, 43, -93
317255385951223, 273902864035952, 222205048141793 @ -5, 34, 92
238669412177419, 184030887653594, 395518973098943 @ -29, 6, -88
373800173262215, 265613443115366, 319536600870043 @ -181, -95, 5
325834328324860, 400609977289966, 237482107289155 @ 70, -249, 35
395545891589302, 396366221941829, 212018576230244 @ -106, -244, 118
79060359491416, 175612392758547, 304904614993482 @ 112, -6, 20
184304991722161, 269213083901132, 182314969449137 @ 144, -28, 160
402529224006137, 445470463762336, 223352953869587 @ -70, -708, 21
340409118374251, 157038486162122, 271921028610191 @ -7, 429, -51
314374759927444, 272342076904982, 264503156998948 @ -68, -41, 34
379864149385448, 476221289742872, 284946383780298 @ -156, -371, -16
160659991514803, 270424234735034, 343018938183851 @ 55, -89, -30
382715923426917, 312499650104197, 251010254449888 @ -145, -46, 28
326444262394039, 313909538220212, 9599882601185 @ 31, -6, 674
28075495353370, 48134605214405, 337532387891225 @ 196, 150, -23
362147646805453, 326092552464338, 113758888400705 @ 114, 167, 700
250858894332919, 335837061137784, 250417346929375 @ 175, -88, 23
299722012722790, 398933732570593, 488586761438011 @ -110, -228, -157
286964335422872, 377786033863913, 99671285251867 @ 30, -194, 331
359922906436261, 340174065491878, 245748198048205 @ -62, -79, 22
384773423982254, 364296359010980, 211664895420662 @ 72, 13, 126
346844476250503, 372588064075892, 256985125658591 @ 135, -126, -105
229479109698269, 92320953358008, 467888548580355 @ -28, 92, -155
395971985552365, 370470283133582, 236592139730555 @ -126, -131, 13
291152150069676, 217557229644671, 308600197842806 @ -12, 70, -48
355008022616900, 250237453990212, 302554208666493 @ 80, 449, -311
339565204991059, 544204410085706, 180175765273319 @ -128, -409, 152
160349135270911, 75193867383962, 264036168311057 @ 55, 123, 56
278628550710151, 183705109945106, 247179615891299 @ -22, 81, 62
71120521330009, 332134986468002, 340596098901103 @ 124, -161, -17
166698816855851, 152836355442138, 188109530967663 @ 93, 81, 143
366807432718969, 281792276055218, 249043555637159 @ -90, 63, 19
277976475380891, 379547446068722, 435269482927207 @ 87, -194, -380
179826248182116, 75227302499197, 163535314440857 @ 206, 350, 201
310765855867771, 154723330372832, 381980899878977 @ 149, 596, -470
379645650249050, 445049722137264, 414892038510781 @ -138, -339, -335
409222241920681, 391802588656841, 254364773207315 @ -37, -222, -621
175775903874585, 228776350495460, 307534145038409 @ 92, -8, -12
399155115926416, 373460960756207, 217563268426382 @ 48, 22, 56
406018611973447, 341521211487278, 259525182698087 @ -113, 193, -269
248187683622967, 156945811398134, 347596443181343 @ -53, 17, -25
365893418227321, 349851886309910, 234795096110901 @ 28, -23, 10
405702676009291, 407778942019722, 264232719948907 @ 13, -493, -751
311904728232119, 278154343109991, 414250724538927 @ -55, -40, -209
120522531182911, 169832350862192, 371344944945173 @ 63, -6, -42
261028778733291, 267231756601834, 296010945155247 @ 23, -25, -19
322673896205904, 289066087091955, 48805274782365 @ 126, 152, 709
393044140402459, 335903602357022, 93548101019275 @ -83, 79, 755
378732467589841, 380126824095947, 253051147763932 @ -89, -182, -22
331329672537549, 315289022930646, 277820667695417 @ 206, 153, -204
375236152547615, 365107447973950, 400861872843663 @ -88, -138, -473
128812674139243, 412602668938730, 120520487402735 @ 80, -243, 209
333851906560813, 229824566104040, 359851686163529 @ -116, -12, -78
362453617755833, 350318552288426, 243200982018401 @ -94, -125, 42
414327832364221, 309484125886979, 359178280646855 @ -197, 226, -681
133751361694151, 259862714710616, 224589308441871 @ 183, -32, 95
226753482043575, 366213393151786, 348272092236169 @ 15, -189, -58
255597224202247, 403206072169646, 527603431176290 @ -55, -233, -218
299874644980451, 304336912191110, 193286009876866 @ 53, -17, 158
207392374393526, 321207764488502, 321752118615752 @ 26, -137, -18
296888492156391, 206977415052222, 278521167733907 @ -40, 60, 12
62964016039966, 40021647758927, 336399289616972 @ 188, 188, -32
140715281909123, 195936574060834, 335285061868949 @ 41, -33, -6
278072476056851, 335234415255362, 382961262381287 @ 59, -107, -231
280736361455940, 184533141010918, 216916892727461 @ 12, 135, 105
255702576213931, 255385597214787, 208722424467292 @ 157, 98, 122
264669858566673, 201083104033562, 232490885591543 @ 66, 139, 75
268045949702677, 318488563680964, 241368339751725 @ -26, -124, 74
347131107904005, 357689002465864, 489107455482090 @ -69, -147, -488
301625510171326, 214066030815267, 302610526489142 @ -56, 36, -18
208648331012645, 492596714006054, 96496930472367 @ 62, -359, 271
162226708208171, 140237626574954, 328699503419759 @ 68, 67, -21
301686962513371, 256611289378682, 319182645698447 @ -46, -14, -51
232397690925883, 208617182104826, 218286374587583 @ 120, 118, 102
362127412360771, 454759182679523, 180715739329379 @ -107, -352, 179
353851887342391, 184223009588692, 470812519707917 @ -137, 62, -240
311920212435307, 208343521844138, 342485997201455 @ -84, 22, -60
371849236111111, 286947594584629, 422222666754290 @ -167, -90, -150
210571388391466, 491129543449122, 263115972101707 @ -8, -325, 59
388601289557836, 339204536154831, 169909467666003 @ -92, 6, 299
262041546925195, 237070494968066, 271036704651023 @ 25, 26, 19
406729204410009, 303418167005849, 217085814715895 @ -141, 358, 87
378732912630527, 503561837595268, 173562168312098 @ -63, -667, 270
28264427688827, 75765204152706, 119405508109555 @ 177, 105, 208
313778149722495, 218411681585670, 269693720605700 @ -63, 47, 24
367656355357511, 336015735605462, 217405310326997 @ 9, 31, 93
276901982527625, 219889240256964, 248759700342075 @ -49, -7, 67
144531585051415, 112787674443836, 214881234940691 @ 151, 162, 109
391506180512800, 361009968228068, 204620553200885 @ 140, 177, 225
259225150255745, 231123001853376, 374048187568153 @ -73, -67, -43
364538187394945, 307942689104822, 141725577726677 @ 70, 229, 496
208546587149173, 75303720275982, 179738668800965 @ -20, 89, 144
208003299981667, 193631878935644, 312481920272246 @ -11, -19, 10
296824995250291, 312191260603222, 308562945070207 @ -77, -124, -5
237257087757109, 193043905236371, 303526980128004 @ 79, 112, -40
402382394787417, 347713685469122, 232211932253295 @ -108, 79, -17
199206178071751, 218754550636062, 244500956776007 @ -14, -54, 81
320605685679435, 298850481131394, 239389300371767 @ -55, -60, 66
101401337453866, 185000763253043, 273194670640136 @ 98, -10, 50
388830942153205, 366957280821536, 231736282046465 @ 22, -22, -36
290527265865846, 180081605070361, 211313157945963 @ 18, 180, 115
299630079330785, 336002779697760, 411550367422737 @ 131, -55, -479
172734979993921, 310169323448036, 26451657961715 @ 188, -84, 425
330312932018809, 317991052905092, 242240673977015 @ 34, -6, 27
386218086666097, 296152486375487, 253504978491893 @ -81, 194, -63
394509091111107, 439651671139810, 366942521467167 @ -90, -480, -719
135131735450581, 342034154673052, 255002261253771 @ 88, -166, 65
235552826266045, 304343416104472, 163979266729541 @ 142, -46, 210
369445242832011, 348855164203352, 223117523315007 @ -19, -44, 71
307393025169307, 222852394115770, 140559921859711 @ 40, 180, 284
238133483754721, 245509089087749, 381294877001705 @ -17, -52, -83
164608307310187, 67522239865898, 368638347902927 @ 69, 155, -69
365399870719291, 352815669375032, 284752637588867 @ -27, -78, -151
322632443739423, 304160218188673, 251485653710244 @ -15, -30, 28
390684005626723, 351239989726022, 518439752424464 @ -155, -121, -642
381325362449447, 362527605500481, 236440656285446 @ 9, -42, -30
345378384518319, 295818656536314, 457662274097405 @ -109, -69, -276
406632939389285, 320146764870130, 207903977445845 @ -148, 207, 144
409919511989905, 322502886192467, 221263447776017 @ -189, 44, 81
223881900244511, 366877762469422, 351198218848597 @ 167, -171, -166
246105456175462, 63276641431902, 266152611884376 @ -26, 159, 50
326395217305523, 367417832094470, 276756715328863 @ 15, -158, -53
361727746934822, 215467397943038, 227475775534105 @ -136, 55, 89
373764209431021, 203823908377621, 261045281670686 @ -137, 146, 18
258485956403427, 222491059836619, 316907228214585 @ -43, -28, -7
259473020241091, 246578920655672, 303290273067857 @ 5, -11, -19
420313086159933, 366443486854933, 317655029655736 @ -229, -112, -338
302997283367496, 383340074873872, 312622227029397 @ -88, -211, -7
397644219318516, 364163796897897, 210043900675707 @ 62, 138, 155
428552565026071, 457895214544850, 392721929630675 @ -247, -373, -301
357283475082367, 154873794884362, 295300150606631 @ 16, 699, -207
325322870416701, 233368764335152, 271016491886887 @ -76, 32, 19
374141467277795, 163209956925442, 346606263548035 @ -111, 359, -227
430915685095616, 402003765181272, 390764491181132 @ -268, -259, -546
242416232578663, 196197845268350, 292283452363775 @ 106, 146, -37
351511719569512, 229957142865223, 187725112275579 @ -110, 56, 155
324560522898048, 342871856423635, 186349998933966 @ 44, -82, 188
358869547404967, 319469211169340, 119634094072931 @ 167, 246, 717
403052936536541, 366552852519797, 235863814020217 @ 23, 154, -223
485364518290031, 454454553722316, 495142085314989 @ -297, -288, -190
245791369315907, 195043992952011, 139716533164225 @ 165, 222, 277
193045203461455, 183843355417739, 339426532449627 @ 25, 10, -29
328919745563896, 279793536536927, 556116718239587 @ -54, -8, -541
324071311114731, 291479592556867, 215519662797838 @ 93, 114, 104
347570747876701, 313217524024508, 263042441441585 @ -42, -20, -16
121694263030699, 162214986035498, 319119527398383 @ 151, 70, -23
283168886013835, 205710099201218, 258351726560243 @ -11, 73, 40
350539770773155, 177024544759834, 357478606944223 @ -125, 95, -101
303370010717810, 271923973404987, 290333974999049 @ -18, -6, -27
322203542754961, 304896348273332, 243846672926147 @ -28, -44, 49
353858914154068, 438998681948736, 297337604650656 @ -146, -279, 8
396890567057833, 338847487225922, 161054349642977 @ -10, 279, 606
7209485524853, 52423663169760, 307419819862807 @ 212, 140, 11
225608341667067, 229523852511658, 310011135453603 @ 137, 83, -70
387861876950291, 349706693148922, 400776553403607 @ -192, -175, -94
135131056714327, 386019578163621, 391782201693981 @ 121, -214, -107
330074548306544, 247660570338385, 332271592402571 @ 54, 230, -261
407438653679147, 382245135140718, 310960584829395 @ -163, -172, -392
299065366061896, 396362587071332, 331900007907797 @ -70, -227, -43
213830772271557, 170608034108180, 306038142344781 @ -9, 13, 13
429059996752759, 291105890796142, 303148333899499 @ -254, 74, -152
140295394784155, 125195730706490, 272864458400111 @ 74, 66, 47
374170613283091, 234483161217062, 372645665110847 @ -17, 502, -621
178843648993198, 209035167153032, 239526171802877 @ 50, -11, 81
203314391670661, 290697265185428, 380236228383359 @ 43, -95, -97
304666172162133, 246551646877251, 318062276486828 @ -85, -42, -18
364919541249095, 177967892380970, 198949926044204 @ -79, 355, 150
444649061161123, 335946089222300, 308492168075963 @ -263, -140, -27
269154065234987, 276959648451167, 291126506675795 @ 29, -26, -21
403605323699221, 412618663082227, 189495956756977 @ -41, -460, 385
319411575773116, 510327391327877, 341077012009952 @ -72, -404, -86
496351863424555, 497673967198826, 429202379353967 @ -344, -383, -219
354379980683815, 328356207744350, 256550820913865 @ 25, 23, -55
136130760710383, 156453136750646, 114092172227567 @ 230, 158, 271
241358643555291, 330346042874682, 207712844803887 @ 23, -135, 119
285104644684647, 352417779275932, 198034968285437 @ 167, -106, 156
438990041320771, 283598689774460, 312001882869329 @ -247, -108, 8
415236437730235, 267212668416410, 550127542617695 @ -221, -59, -327
410834786720959, 290338922614187, 249955036396163 @ -151, 634, -197
122927810378796, 128730135726442, 394248390058687 @ 62, 35, -65
388409947492647, 360966204541014, 226428037710643 @ -36, -34, 32
351263135104981, 287988846876812, 205217697432587 @ 124, 310, 153
190397369714274, 245174001611269, 241818186272278 @ 72, -30, 74
392061596105441, 341117417779297, 204947075653907 @ -109, -6, 147
278519602190430, 267462182098597, 385292207189845 @ -28, -46, -131
339233403438871, 319266754555682, 249664482462227 @ -9, -25, 13
247496456731201, 316439551028207, 278638933152587 @ -5, -124, 27
308289553960916, 301606782288987, 406198920632567 @ -102, -120, -105
171396278431153, 286194931214432, 136290574873172 @ 79, -91, 206
347258057533595, 406960289651002, 408811010472663 @ 107, -291, -788
92082748781270, 193380649695803, 69093705820524 @ 234, 58, 314
389391058731046, 351793984516382, 239566403723627 @ 20, 103, -101
359884413564963, 263681998382322, 164910623193015 @ -28, 204, 272
291038604762387, 65664137587854, 192632331936091 @ 27, 422, 152
390261722850463, 549192218373971, 311695919240000 @ -143, -668, -168
249516041081911, 391746659362922, 148207029301457 @ -5, -221, 196
368120301721219, 294526417507042, 291934461217695 @ -86, 44, -103
378601434017998, 288300864885584, 312942003226679 @ -164, -63, -41
341546511659873, 340765668013711, 264968847279080 @ 51, -40, -72
406619280446511, 372680575874092, 237315499981345 @ -57, 24, -196
389984292085879, 338605388815733, 222061816456084 @ -23, 142, 52
401551580294980, 344104821798716, 356695273458212 @ -174, -83, -304
409848514874386, 545944723938812, 294072053372357 @ -196, -699, -139
238154985788203, 251217843927518, 309239631491837 @ 29, -23, -24
388312482560797, 169689228997394, 164165311350761 @ -106, 631, 300
326989072080919, 206027187994178, 350695443678983 @ -135, -37, -25
183786250029153, 161441724986202, 292386221844911 @ 60, 59, 15
353390751241853, 360651605393240, 324696046714822 @ -9, -119, -254
291323766143796, 135621216707137, 326230681697617 @ -88, 56, -11
356347707311041, 378538430468438, 195136213127783 @ 23, -169, 183
364886634069223, 366456093930311, 253252192157207 @ 49, -94, -89
373546650448878, 381179776987807, 205739524694887 @ 14, -166, 151
55436542145707, 387742128971498, 206416601873615 @ 137, -217, 118
373742245916518, 373090825088852, 263262258762194 @ -54, -151, -76
326070749023616, 97795071598108, 340962689947285 @ 48, 641, -263
139639177238878, 241213330342260, 183499229711126 @ 82, -55, 144
291815214667231, 326088406492122, 258400433275105 @ 163, -21, -26
374454933278451, 296295156161142, 263948534196357 @ 65, 393, -214
181423137208587, 414537348460254, 261635603149117 @ 45, -247, 56
417131754211648, 318880223151587, 279374829951578 @ -216, 74, -156
349532199052591, 324778460588922, 261976474169757 @ -17, -21, -34
402865242502891, 370625280018410, 212004086418479 @ 48, 121, 134
176838424156516, 238507170404918, 256880504539235 @ 198, 47, 35
360020081312971, 240679125070814, 214172389139261 @ -67, 183, 109
335484964041595, 64663888204658, 226563161458199 @ 17, 725, 73
210390668762731, 231660795982394, 464026232079527 @ 53, -7, -224
356622122698203, 316021676084898, 207910574965547 @ -55, -15, 126
344541028493583, 327459530716342, 188628066152069 @ -145, -151, 138
350330679629951, 148842141054734, 281306937531939 @ -57, 373, -55
369863033800950, 253338397158411, 138355642083279 @ 50, 546, 527
345876350420926, 175781094242592, 480405583002637 @ -140, 33, -203
290394191993731, 442090121051862, 303323568788857 @ -47, -291, -14
317016478625816, 214609679490407, 223376045781782 @ -72, 46, 96
238959415850021, 217384204269337, 334639071032757 @ -33, -34, -19
341859737627341, 312717734956466, 274775931900461 @ -77, -69, -7
246465816222901, 371931460329506, 437996785770655 @ -17, -197, -161
413583904007131, 353135785114262, 253329243126887 @ -135, 346, -475
280256492866765, 153004662854228, 320401818111683 @ -13, 145, -53
386414176637071, 385900166488042, 217626696812427 @ 139, -157, 65
381669932936015, 353189775871970, 226276824555591 @ -25, -17, 43
207238693976251, 151134237904106, 197867692464287 @ -22, 11, 126
10868238730187, 309748079927666, 120290341070415 @ 177, -140, 203
341033076224472, 241023348049802, 285960123628046 @ 24, 259, -120
246235808164471, 243437578732262, 235214015838467 @ 20, -10, 80
380726574267427, 220438697531366, 246026391306827 @ -161, 68, 56
267561116021701, 268354580924526, 284492119538949 @ -32, -63, 20
387147934186399, 415674127835282, 309931986230459 @ -186, -251, -10
372378961223081, 353808159961077, 230618332743187 @ 27, -18, 19
335191876546759, 295780596111380, 390493225889735 @ 35, 76, -437
436417569387431, 437665798715710, 343607657089707 @ -262, -318, -164
141275060501488, 359957462978464, 215097645657789 @ 106, -183, 109
268568116618912, 297740962395419, 435676409644028 @ 16, -70, -246
380044134727141, 264371705640842, 265435969495123 @ -152, 19, 13
311931942803755, 319802082721898, 306727652889935 @ -35, -93, -55
14805605333923, 64297940155954, 125742764015035 @ 295, 201, 224
227619235560379, 205578379975282, 290489538735351 @ -5, -6, 22
261790862434201, 262289675567934, 378256387332458 @ -17, -49, -108
238324918165671, 162143469274754, 424384726079787 @ -42, 13, -104
305570105502203, 211238254651908, 229007989458119 @ -51, 57, 87
368607647803443, 479528646510678, 377228238133367 @ -105, -430, -279
134786111686215, 408224271853042, 54415569528949 @ 119, -241, 304
200895906123145, 303671619980555, 295737650976707 @ 39, -114, 11
403955250444787, 388115547016290, 222234441981583 @ 40, -160, -37
389495355644062, 418611208941481, 276573666080934 @ -140, -298, -70
345458099009851, 250404312727586, 239992640328407 @ -87, 45, 61
404198497378209, 319587976356834, 318795322130411 @ -96, 383, -771
294394653121615, 219891653001722, 290759282921147 @ -8, 79, -24
356217954556966, 361580921545642, 447680337795922 @ -92, -157, -386
210698356285555, 182596207883186, 102071280428192 @ -11, -5, 226
353707675498172, 279424144802785, 281131132911930 @ -58, 66, -62
175333305826996, 224300669373432, 292157412768897 @ 214, 81, -31
409810530260833, 330082954692680, 262659891151901 @ -206, -92, 8"""

test_area = np.array([[200000000000000, 400000000000000], [200000000000000, 400000000000000]])

In [141]:
hail = np.array([
    [
        [int(x) for x in coords.split(', ')]
        for coords in line.split(' @ ')
    ]
    for line in input.split('\n')
])

In [160]:
def check_intersect(h1, h2, num_axis=3, spec=False):
    h = np.array([h1, h2])
    vel_mat = np.array([[h[0, 1, ax], -h[1, 1, ax]] for ax in range(num_axis)], dtype=np.int64)
    pos_vec = np.array([[h[1, 0, ax] - h[0, 0, ax]] for ax in range(num_axis)], dtype=np.int64)
    try:
        t = scipy.linalg.solve(vel_mat, pos_vec)
        if spec and (t < 0).any():
            return False, None, None
        pos = (h[0, 0] + t[0] * h[0, 1])[:2]
        if spec and ((pos < test_area[:, 0]).any() or (pos > test_area[:, 1]).any()):
            return False, None, None
        return True, t, pos
    except:
        return False, None, None

In [143]:
total = 0

for i in range(len(hail)):
    for j in range(i+1, len(hail)):
        res, t, pos = check_intersect(hail[i], hail[j], 2, True)
        if res:
            total+=1
            print(f"Hail: {i}-{j}, T: {t[:, 0]}, pos: {pos}")
            
total

Hail: 0-20, T: [4.17041582e+10 2.32680672e+11], pos: [3.67738713e+14 3.40706852e+14]
Hail: 0-32, T: [1.17156701e+11 2.01827473e+11], pos: [3.74152179e+14 3.47120318e+14]
Hail: 0-35, T: [3.60683115e+11 1.09675706e+11], pos: [3.94851925e+14 3.67820064e+14]
Hail: 0-43, T: [2.04261780e+11 1.70249687e+11], pos: [3.81556111e+14 3.54524250e+14]
Hail: 0-48, T: [3.36219261e+11 1.11098237e+11], pos: [3.92772497e+14 3.65740636e+14]
Hail: 0-49, T: [1.17038381e+11 2.02204785e+11], pos: [3.74142122e+14 3.47110261e+14]
Hail: 0-53, T: [9.02127431e+10 2.10674005e+11], pos: [3.71861943e+14 3.44830082e+14]
Hail: 0-67, T: [3.29287512e+11 1.22436404e+11], pos: [3.92183298e+14 3.65151437e+14]
Hail: 0-69, T: [9.09819358e+10 2.15496648e+11], pos: [3.71927324e+14 3.44895463e+14]
Hail: 0-75, T: [1.57932117e+11 1.85856032e+11], pos: [3.77618090e+14 3.50586229e+14]
Hail: 0-77, T: [1.15957294e+11 2.07381346e+11], pos: [3.74050230e+14 3.47018369e+14]
Hail: 0-82, T: [1.63474811e+11 1.83952354e+11], pos: [3.78089219e

17244

In [102]:
# too low
1658

1658

In [103]:
# too low
4270

4270

## Part 2

In [180]:
h0 = hail[0]
h1 = hail[1]
relative_state1 = h1 - h0

vecs1 = [relative_state1[0], relative_state1.sum(axis=0)]
plane_norm1 = np.cross(*vecs1)
plane_norm1 //= np.gcd.reduce(plane_norm1)
plane_norm1

array([ 45919, -76766,  25314])

In [181]:
h2 = hail[2]
relative_state2 = h2 - h0

vecs2 = [relative_state2[0], relative_state2.sum(axis=0)]
plane_norm2 = np.cross(*vecs2)
plane_norm2 //= np.gcd.reduce(plane_norm2)
plane_norm2

array([ 42416, -24555, -15801])

In [182]:
relative_rock_dir = np.cross(plane_norm1, plane_norm2)
relative_rock_dir //= np.gcd.reduce(relative_rock_dir)
relative_rock_dir

array([156, 153, 181])

In [187]:
res1, t1, pos1 = check_intersect(np.array([[0, 0, 0], relative_rock_dir], dtype=np.int64), relative_state1, 2)
res1, t1, pos1

(True,
 array([[-7.71502037e+11],
        [ 5.64132262e+11]]),
 array([-1.20354318e+14, -1.18039812e+14]))

In [188]:
res2, t2, pos2 = check_intersect(np.array([[0, 0, 0], relative_rock_dir]), relative_state2, 2)
res2, t2, pos2

(True,
 array([[-8.14127012e+11],
        [ 5.85444750e+11]]),
 array([-1.27003814e+14, -1.24561433e+14]))

In [196]:
vel_mod = (t1[0][0] - t2[0][0]) / (t1[1][0] - t2[1][0])
vel_mod = vel_mod.astype(np.int64)
vel_mod

-2

In [197]:
rel_vel = relative_rock_dir * vel_mod
rel_vel

array([-312, -306, -362])

In [199]:
dt = (t1[0][0] / vel_mod - t1[1][0]).astype(np.int64)
dt

-178381243424

In [200]:
rel_start_pos = rel_vel * dt
rel_start_pos

array([55654947948288, 54584660487744, 64574010119488])

In [201]:
start = rel_start_pos + h0[0]
vel = rel_vel + h0[1]
start, vel

(array([419848807765291, 391746659362922, 213424530058607]),
 array([-227, -221,  111]))

In [202]:
sum(start)

1025019997186820